### ISSUE TITLE
Restrict the IPs that can connect to instances

### ISSUE THREAD

**Issue by mccalluc** [WGBH-MLA/aws-wrapper#15]
Limit to only the WGBH IP range (_plus travis_). If something really needs to be done from off-site, that's what VPNs are for. (Also, we should not be counting on the longevity of any particular instance, so it shouldn't be the end of the world if we can't connect and have to start over.)

**Comment by mccalluc** [comment]
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/authorizing-access-to-an-instance.html

**Comment by afred** [comment]
If the declarative way involves writing a template for iptables configuration, i don't have the know how for that.

if aws-sdk allows you to manage security groups, then i'd be in favor of going that route.

Whey you say "Restrict the IPs that can connect", I assume you mean SSH on port 22?

**Comment by afred** [comment]
not that I'm opposed to learning more about iptables config... i just don't know much beyond the few times i've had to tweak it, e.g. to open up port 22 on new CentOS installs.

a declarative config template would be appealing, but right now i'm not confident that I could look at a config and be sure it's secure.

**Comment by afred** [comment]
^ hmm... and after running `iptable -L` on some EC2 instances, it shows that no rules have been defined...
```
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination 
```
So I'm not sure where the security group rules are being applied, but perhaps not at the instance layer at all?

**Comment by mccalluc** [comment]
The ip table result doesn't surprise me: The AWS firewalling would be outside the instance. Their API can't rely on any particular operating system running on the instance: could be windows or DOS for all they know.

I'll figure it out in AWS.

**Comment by sroosa** [comment]
stale
