### ISSUE TITLE
Clean up unused EBS volumes

### ISSUE THREAD

**Issue by afred** [WGBH-MLA/aws-wrapper#46]
This ticket isn't specific to aws-wrapper, but it needs to be done, so putting it here so it's part of the workflow. Is there a better place for tracking infrastructure tasks no related to any single project?

**Done when**
1. we've gone through all EBS volumes and determine which each is being used for
2. we are certain we have backups of the ones we need backups for
3. we've deleted the ones we know no longer need
4. we've asked about the ones we're unsure of

**Comment by sroosa** [comment]
Stale
