### ISSUE TITLE
Should EC2 instances support PING?

### ISSUE THREAD

**Issue by mccalluc** [WGBH-MLA/aws-wrapper#76]
Out of the box, EC2 does not support ping requests. This is conservative, and reasonable,  but I also feel like ping is a fairly common health check, and we'll probably confuse ourselves at some point if it's not supported. Thoughts? @Muraszko / @afred ?

http://stackoverflow.com/questions/21981796/cannot-ping-aws-ec2-instance

**Comment by afred** [comment]
👍

**Comment by sroosa** [comment]
Stale
